version: '3.0'
services:
   minio:
     image: bitnami/minio
     ports:
       - '9000:9000'
       - '9001:9001'
     environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
     volumes:
       - 'minio_data:/data'
       - 'minio_config:/root/.minio'

volumes:
 minio_data:
 minio_config:
